# Generated by Django 4.2.5 on 2023-10-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=30)),
                ('nome_empresa', models.CharField(max_length=30)),
                ('categoria_empresa', models.CharField(max_length=30)),
            ],
        ),
    ]
